# Removes build output (bin/ and obj/) so the working tree stays tidy, and reports what it removes.
#
# Build output is git-ignored (see .gitignore: **/bin/, **/obj/) and regenerated by the next build, so
# removing it is safe. This exists as a script because the output used to accumulate silently: Run.ps1
# writes a flat directory (bin/window-regression via -p:OutDir=), while a plain `dotnet build` writes the
# standard layout bin/<Configuration>/<TFM>/. Both layouts end up side by side under the same bin/, so
# every extra output directory a scenario was ever given leaves a sibling behind.
#
# Usage:
#   .\Clean-BuildOutput.ps1                 # list and remove tests/*/bin and tests/*/obj
#   .\Clean-BuildOutput.ps1 -Scope all      # include src and tools as well
#   .\Clean-BuildOutput.ps1 -Scope src      # only src
#   .\Clean-BuildOutput.ps1 -Scope tools    # only tools
#   .\Clean-BuildOutput.ps1 -WhatIf         # preview only, remove nothing
#
# obj/ holds the NuGet restore cache and compile intermediates, so removing it makes the next build do a
# full restore. Use -Scope all -WhatIf first if you only want to see the numbers.
param(
    [ValidateSet('tests', 'src', 'tools', 'all')][string]$Scope = 'tests',
    [switch]$WhatIf
)
$ErrorActionPreference = 'Stop'
$repoRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$roots = switch ($Scope) {
    'tests' { @(Join-Path $repoRoot 'tests') }
    'src'   { @(Join-Path $repoRoot 'src') }
    'tools' { @(Join-Path $repoRoot 'tools') }
    'all'   { @((Join-Path $repoRoot 'src'), (Join-Path $repoRoot 'tests'), (Join-Path $repoRoot 'tools')) }
}

$targets = @()
foreach ($root in $roots) {
    if (-not (Test-Path -LiteralPath $root)) { continue }
    Get-ChildItem -LiteralPath $root -Directory -Recurse -ErrorAction SilentlyContinue |
        Where-Object { $_.Name -in @('bin', 'obj') } |
        ForEach-Object {
            $size = (Get-ChildItem -LiteralPath $_.FullName -Recurse -File -ErrorAction SilentlyContinue |
                Measure-Object -Property Length -Sum).Sum
            $targets += [pscustomobject]@{ Path = $_.FullName; Size = [long]$size }
        }
}

if ($targets.Count -eq 0) {
    Write-Output "Nothing to clean under '$Scope'."
    exit 0
}

$total = ($targets | Measure-Object -Property Size -Sum).Sum
foreach ($target in ($targets | Sort-Object Size -Descending)) {
    Write-Output ('  {0,9:N1} MB  {1}' -f ($target.Size / 1MB), $target.Path.Replace($repoRoot + '\', ''))
}
Write-Output ('  {0} directories, {1:N1} MB total (scope: {2})' -f $targets.Count, ($total / 1MB), $Scope)

if ($WhatIf) {
    Write-Output 'WhatIf: nothing removed.'
    exit 0
}

# Deepest paths first: removing a parent bin/ would otherwise make a nested target disappear mid-loop.
foreach ($target in ($targets | Sort-Object { $_.Path.Length } -Descending)) {
    if (Test-Path -LiteralPath $target.Path) {
        Remove-Item -LiteralPath $target.Path -Recurse -Force
    }
}
Write-Output ('Removed {0} directories, freed {1:N1} MB.' -f $targets.Count, ($total / 1MB))
