<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Mtp.Host</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Mtp.Platform.Core/Mtp.Platform.Core.csproj" />
    <ProjectReference Include="../Mtp.Contracts/Mtp.Contracts.csproj" />
    <ProjectReference Include="../Mtp.Transport/Mtp.Transport.csproj" />
    <InternalsVisibleTo Include="Mtp.Host" />
    <InternalsVisibleTo Include="Mtp.Host.Legacy.Runtime" />
    <InternalsVisibleTo Include="Mtp.Host.Legacy.Windows" />
    <InternalsVisibleTo Include="Mtp.Platform.Core.Tests" />
    <InternalsVisibleTo Include="Mtp.Host.Windows.Tests" />
    <InternalsVisibleTo Include="Mtp.Host.WindowTests" />
  </ItemGroup>
</Project>
