<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Mtp.Contracts/Mtp.Contracts.csproj" />
    <ProjectReference Include="../Mtp.Transport/Mtp.Transport.csproj" />
  </ItemGroup>
</Project>
